export interface IBuild {
  bathroom_number: number;
  bedroom_number: number;
  car_spaces: number;
  commission: number;
  construction_year: number;
  datasource_name: string;
  floor: number;
  img_height: number;
  img_url: string;
  img_width: number;
  keywords: string;
  latitude: number;
  lister_name: string;
  lister_url: string;
  listing_type: string;
  location_accuracy: number;
  longitude: number;
  price: number;
  price_currency: string
  price_formatted: string;
  price_high: number;
  price_low: number;
  price_type: string;
  property_type: string;
  size: number;
  size_type: string;
  summary: string;
  thumb_height: number;
  thumb_url: string;
  thumb_width: number;
  title: string;
  updated_in_days: number;
  updated_in_days_formatted: string;
}
